blue:
    -
        conditions:
            -
                name: operator
                values: [Tele2]
                exclude: true
            -
                name: region
                values: [Local]
        price: 1.20
    -
        conditions:
            -
                name: operator
                values: [Tele2]
            -
                name: region
                values: [Local]
                exclude: true
        price: 1.50
    -
        conditions:
            -
                name: operator
                values: [Tele2]
                exclude: true
            -
                name: region
                values: [Local]
                exclude: true
        price: 9.00
red:
    -
        conditions:
            -
                name: operator
                values: [Tele2]
            -
                name: region
                values: [Local]
        price: 0.19
    -
        conditions:
            -
                name: operator
                values: [Tele2]
                exclude: true
            -
                name: region
                values: [Local]
        price: 0.49
    -
        conditions:
            -
                name: operator
                values: [Tele2]
            -
                name: region
                values: [Local]
                exclude: true
        price: 1.50
    -
        conditions:
            -
                name: operator
                values: [Tele2]
                exclude: true
            -
                name: region
                values: [Local]
                exclude: true
        price: 9.00
green:
    -
        conditions:
            -
                name: operator
                values: [Tele2]
            -
                name: region
                values: [Local]
        price: 0.50
    -
        conditions:
            -
                name: operator
                values: [Tele2]
                exclude: true
            -
                name: region
                values: [Local]
        price: 1.50
    -
        conditions:
            -
                name: operator
                values: [Tele2]
            -
                name: region
                values: [Local]
                exclude: true
        price: 1.50
    -
        conditions:
            -
                name: operator
                values: [Tele2]
                exclude: true
            -
                name: region
                values: [Local]
                exclude: true
        price: 4.30
